# CORE_MEM_ADDR_WIDTH_IN_32B = 14
# CORE_MEM_ADDR_WIDTH_IN_8B = CORE_MEM_ADDR_WIDTH_IN_32B + 2
# CORE_MEM_ADDR_WIDTH_IN_1B = CORE_MEM_ADDR_WIDTH_IN_32B + 5

MAX_CORE_MEM_ADDR_IN_32B = 0x6000
MAX_CORE_MEM_ADDR_IN_8B = MAX_CORE_MEM_ADDR_IN_32B * 4
MAX_CORE_MEM_ADDR_IN_1B = MAX_CORE_MEM_ADDR_IN_32B * 32